name: Build

on: push

jobs:
  build-webos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Package
        run: npm run package

      - name: Build manifest
        run: npm run build-manifest

      - name: Upload artiacts
        uses: actions/upload-artifact@v3
        with:
          name: webos-snapshot
          path: "dist/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
